spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/zspoa_activiti?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  application:
    name: zspoa-activiti
  redis:
    host: 8.129.217.148
    port: 6888
  cache:
    redis:
      cache-null-values: true
      key-prefix: ACTI_
      time-to-live: 3600000
#设置空值存储，前缀，过期时间：毫秒为单位
  session:
    store-type: redis
#springsesssion的配置
server:
  port: 7000
  servlet:
    session:
      timeout: 30m
#      spring session的超时时间