spring:
  datasource:
    username: root
    data-password: 123456
    url: jdbc:mysql://8.129.217.148:3310/zspoa_activiti?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  application:
    name: zspoa-activiti
server:
  port: 7000