spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/zspoa_activiti?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  application:
    name: zspoa-activiti
  redis:
    host: 8.129.217.148
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 3600
server:
  port: 7000