spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  application:
    name: zspoa-search
  redis:
    host: 8.129.217.148
    port: 6888
  cache:
    redis:
      cache-null-values: true
      key-prefix: ACTI_
      time-to-live: 3600000