spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/zspoa_member?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  application:
    name: zspoa-member
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 9000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
